import { Guide, Deal, TodayCard, Author } from './types';

export const authors: Record<string, Author> = {
  'elara-wren': {
    slug: 'elara-wren',
    name: 'Elara Wren',
    bio: 'Beauty editor obsessed with the science of skincare.',
    image: '/avatars/elara.jpg',
  },
  'maya-patel': {
    slug: 'maya-patel',
    name: 'Maya Patel',
    bio: 'Wellness writer and sleep researcher.',
    image: '/avatars/maya.jpg',
  },
  'jordan-clark': {
    slug: 'jordan-clark',
    name: 'Jordan Clark',
    bio: 'Hair care specialist and product tester.',
    image: '/avatars/jordan.jpg',
  },
};

export const guides: Guide[] = [
  {
    slug: '10-face-oils-repurchase',
    title: '10 face oils we\'d actually repurchase tomorrow',
    category: 'skincare',
    subCategory: 'Serums & Oils',
    heroImage: { src: '/images/oils.jpg', alt: 'Face oils', tone: 'clay' },
    readMinutes: 8,
    publishedAt: '2026-05-26',
    updatedAt: '2026-05-26',
    author: authors['elara-wren'],
    rating: 4.8,
    reviewCount: 942,
    picksTestedCount: 10,
    excerpt: 'After 6 weeks of testing, here are the face oils that actually improved our skin barrier.',
    picks: [
      {
        rank: 1,
        productTitle: 'Marula Face Oil',
        productImage: { src: '/images/marula.jpg', alt: 'Marula oil bottle' },
        affiliateUrl: 'https://amazon.com/s?k=marula+oil',
        priceFrom: 18,
        badge: 'editor-pick',
      },
      {
        rank: 2,
        productTitle: 'Rosehip Seed Oil',
        productImage: { src: '/images/rosehip.jpg', alt: 'Rosehip oil' },
        affiliateUrl: 'https://amazon.com/s?k=rosehip+oil',
        priceFrom: 12,
      },
      {
        rank: 3,
        productTitle: 'Jojoba Oil',
        productImage: { src: '/images/jojoba.jpg', alt: 'Jojoba oil' },
        affiliateUrl: 'https://amazon.com/s?k=jojoba+oil',
        priceFrom: 8,
      },
      {
        rank: 4,
        productTitle: 'Squalane Oil',
        productImage: { src: '/images/squalane.jpg', alt: 'Squalane oil' },
        affiliateUrl: 'https://amazon.com/s?k=squalane',
        priceFrom: 15,
      },
      {
        rank: 5,
        productTitle: 'Vitamin E Oil',
        productImage: { src: '/images/vit-e.jpg', alt: 'Vitamin E oil' },
        affiliateUrl: 'https://amazon.com/s?k=vitamin+e+oil',
        priceFrom: 6,
      },
      {
        rank: 6,
        productTitle: 'Argan Oil',
        productImage: { src: '/images/argan.jpg', alt: 'Argan oil' },
        affiliateUrl: 'https://amazon.com/s?k=argan+oil',
        priceFrom: 14,
      },
      {
        rank: 7,
        productTitle: 'Sea Buckthorn Oil',
        productImage: { src: '/images/buckthorn.jpg', alt: 'Sea buckthorn oil' },
        affiliateUrl: 'https://amazon.com/s?k=sea+buckthorn',
        priceFrom: 22,
      },
      {
        rank: 8,
        productTitle: 'Apricot Kernel Oil',
        productImage: { src: '/images/apricot.jpg', alt: 'Apricot oil' },
        affiliateUrl: 'https://amazon.com/s?k=apricot+kernel+oil',
        priceFrom: 10,
      },
      {
        rank: 9,
        productTitle: 'Camellia Oil',
        productImage: { src: '/images/camellia.jpg', alt: 'Camellia oil' },
        affiliateUrl: 'https://amazon.com/s?k=camellia+oil',
        priceFrom: 16,
      },
      {
        rank: 10,
        productTitle: 'Hemp Seed Oil',
        productImage: { src: '/images/hemp.jpg', alt: 'Hemp seed oil' },
        affiliateUrl: 'https://amazon.com/s?k=hemp+seed+oil',
        priceFrom: 11,
      },
    ],
  },
  {
    slug: '10-silk-pillowcases',
    title: '10 silk pillowcases worth the splurge',
    category: 'self-care',
    heroImage: { src: '/images/pillowcase.jpg', alt: 'Silk pillowcase', tone: 'sage' },
    readMinutes: 6,
    publishedAt: '2026-05-20',
    updatedAt: '2026-05-20',
    author: authors['maya-patel'],
    rating: 4.7,
    reviewCount: 847,
    excerpt: 'We tested luxury pillowcases and found the ones that actually reduce friction and last years.',
    picks: [
      {
        rank: 1,
        productTitle: 'Premium Silk Pillowcase 100%',
        productImage: { src: '/images/silk1.jpg', alt: 'Silk pillowcase' },
        affiliateUrl: 'https://amazon.com/s?k=silk+pillowcase',
        priceFrom: 45,
        badge: 'best-value',
      },
      {
        rank: 2,
        productTitle: 'Mulberry Silk Pillowcase',
        productImage: { src: '/images/silk2.jpg', alt: 'Mulberry silk' },
        affiliateUrl: 'https://amazon.com/s?k=mulberry+silk',
        priceFrom: 65,
      },
      {
        rank: 3,
        productTitle: 'Charmeuse Silk Pillowcase',
        productImage: { src: '/images/silk3.jpg', alt: 'Charmeuse' },
        affiliateUrl: 'https://amazon.com/s?k=charmeuse+silk',
        priceFrom: 38,
      },
      {
        rank: 4,
        productTitle: 'Luxury Silk Pillowcase Set',
        productImage: { src: '/images/silk4.jpg', alt: 'Silk set' },
        affiliateUrl: 'https://amazon.com/s?k=silk+pillowcase+set',
        priceFrom: 78,
      },
      {
        rank: 5,
        productTitle: 'Bamboo Silk Blend',
        productImage: { src: '/images/silk5.jpg', alt: 'Bamboo silk' },
        affiliateUrl: 'https://amazon.com/s?k=bamboo+silk',
        priceFrom: 28,
      },
      {
        rank: 6,
        productTitle: 'Silk & Satin Pillowcase',
        productImage: { src: '/images/silk6.jpg', alt: 'Silk satin' },
        affiliateUrl: 'https://amazon.com/s?k=silk+satin',
        priceFrom: 35,
      },
      {
        rank: 7,
        productTitle: 'Premium Grade Silk',
        productImage: { src: '/images/silk7.jpg', alt: 'Premium silk' },
        affiliateUrl: 'https://amazon.com/s?k=premium+silk',
        priceFrom: 55,
      },
      {
        rank: 8,
        productTitle: 'Hypoallergenic Silk',
        productImage: { src: '/images/silk8.jpg', alt: 'Hypoallergenic' },
        affiliateUrl: 'https://amazon.com/s?k=hypoallergenic+silk',
        priceFrom: 42,
      },
      {
        rank: 9,
        productTitle: 'Anti-Wrinkle Silk',
        productImage: { src: '/images/silk9.jpg', alt: 'Anti-wrinkle' },
        affiliateUrl: 'https://amazon.com/s?k=anti+wrinkle+silk',
        priceFrom: 48,
      },
      {
        rank: 10,
        productTitle: 'Temperature Silk',
        productImage: { src: '/images/silk10.jpg', alt: 'Temperature silk' },
        affiliateUrl: 'https://amazon.com/s?k=temperature+silk',
        priceFrom: 52,
      },
    ],
  },
  {
    slug: '10-vitamin-c-serums',
    title: '10 vitamin C serums tested over 6 weeks',
    category: 'skincare',
    subCategory: 'Serums & Essences',
    heroImage: { src: '/images/vitc.jpg', alt: 'Vitamin C serums', tone: 'sand' },
    readMinutes: 9,
    publishedAt: '2026-05-18',
    updatedAt: '2026-05-18',
    author: authors['elara-wren'],
    rating: 4.9,
    reviewCount: 1205,
    excerpt: 'We tested every major vitamin C formulation for stability, brightness, and irritation.',
    picks: Array.from({ length: 10 }, (_, i) => ({
      rank: i + 1,
      productTitle: `Vitamin C Serum ${i + 1}`,
      productImage: { src: `/images/vitc${i + 1}.jpg`, alt: `Vitamin C serum ${i + 1}` },
      affiliateUrl: `https://amazon.com/s?k=vitamin+c+serum`,
      priceFrom: 20 + i * 5,
    })),
  },
  {
    slug: '10-magnesium-sprays',
    title: '10 magnesium sprays our editors swear by',
    category: 'wellness',
    subCategory: 'Sleep & Relaxation',
    heroImage: { src: '/images/magnesium.jpg', alt: 'Magnesium spray', tone: 'rose' },
    readMinutes: 7,
    publishedAt: '2026-05-16',
    updatedAt: '2026-05-16',
    author: authors['maya-patel'],
    rating: 4.7,
    picksTestedCount: 62,
    excerpt: 'Real magnesium sprays that actually help us sleep better. We tested absorption, taste, and effectiveness.',
    picks: Array.from({ length: 10 }, (_, i) => ({
      rank: i + 1,
      productTitle: `Magnesium Spray ${i + 1}`,
      productImage: { src: `/images/mag${i + 1}.jpg`, alt: `Magnesium spray ${i + 1}` },
      affiliateUrl: `https://amazon.com/s?k=magnesium+spray`,
      priceFrom: 15 + i * 3,
    })),
  },
];

export const todayCards: TodayCard[] = [
  {
    meta: "Editor's drop · May 26",
    title: "Today's pick: marula oil",
    href: '/guides/10-face-oils-repurchase',
    tone: 'clay',
  },
  {
    meta: 'Daily ritual',
    title: 'A slower evening routine',
    href: '/guides/10-magnesium-sprays',
    tone: 'sage',
  },
  {
    meta: 'This month',
    title: 'Cozy bath edit · May',
    href: '/',
    tone: 'sand',
  },
  {
    meta: 'To gift',
    title: '10 self-care gifts under $40',
    href: '/',
    tone: 'rose',
  },
  {
    meta: 'Reader fav',
    title: 'The silk pillowcase debate',
    href: '/guides/10-silk-pillowcases',
    tone: 'mauve',
  },
  {
    meta: 'Game of the day',
    title: 'Guess the ingredient',
    href: '/',
    tone: 'slate',
  },
];

export const deals: Deal[] = [
  {
    product: guides[0].picks[0],
    guideSlug: guides[0].slug,
    rankInGuide: 1,
    priceNow: 18,
    priceWas: 32,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const trendingGuides: Guide[] = guides;

export const categor = [
  { name: 'Skincare', slug: 'skincare' },
  { name: 'Hair', slug: 'hair' },
  { name: 'Wellness', slug: 'wellness' },
  { name: 'Sleep', slug: 'sleep' },
  { name: 'Body', slug: 'body' },
  { name: 'Self-care', slug: 'self-care' },
  { name: 'Home', slug: 'home' },
];
