import { Guide, Deal, TodayCard, Author } from './types';

export const authors: Record<string, Author> = {
  'elara-wren': {
    slug: 'elara-wren',
    name: 'Elara Wren',
    bio: 'Beauty editor obsessed with the science of skincare.',
    image: '/avatars/elara.jpg',
  },
  'maya-patel': {
    slug: 'maya-patel',
    name: 'Maya Patel',
    bio: 'Wellness writer and sleep researcher.',
    image: '/avatars/maya.jpg',
  },
  'jordan-clark': {
    slug: 'jordan-clark',
    name: 'Jordan Clark',
    bio: 'Hair care specialist and product tester.',
    image: '/avatars/jordan.jpg',
  },
};

export const guides: Guide[] = [
  {
    slug: '10-face-oils-repurchase',
    title: '10 face oils we\'d actually repurchase tomorrow',
    category: 'skincare',
    subCategory: 'Serums & Oils',
    heroImage: { src: '/images/oils.jpg', alt: 'Face oils', tone: 'clay' },
    readMinutes: 8,
    publishedAt: '2026-05-26',
    updatedAt: '2026-05-26',
    author: authors['elara-wren'],
    rating: 4.8,
    reviewCount: 942,
    picksTestedCount: 10,
    excerpt: 'After 6 weeks of testing, here are the face oils that actually improved our skin barrier.',
    picks: [
      {
        rank: 1,
        productTitle: 'Marula Face Oil',
        productImage: { src: '/images/marula.jpg', alt: 'Marula oil bottle' },
        affiliateUrl: 'https://amazon.com/s?k=marula+oil',
        priceFrom: 18,
        badge: 'editor-pick',
      },
      {
        rank: 2,
        productTitle: 'Rosehip Seed Oil',
        productImage: { src: '/images/rosehip.jpg', alt: 'Rosehip oil' },
        affiliateUrl: 'https://amazon.com/s?k=rosehip+oil',
        priceFrom: 12,
      },
      {
        rank: 3,
        productTitle: 'Jojoba Oil',
        productImage: { src: '/images/jojoba.jpg', alt: 'Jojoba oil' },
        affiliateUrl: 'https://amazon.com/s?k=jojoba+oil',
        priceFrom: 8,
      },
      {
        rank: 4,
        productTitle: 'Squalane Oil',
        productImage: { src: '/images/squalane.jpg', alt: 'Squalane oil' },
        affiliateUrl: 'https://amazon.com/s?k=squalane',
        priceFrom: 15,
      },
      {
        rank: 5,
        productTitle: 'Vitamin E Oil',
        productImage: { src: '/images/vit-e.jpg', alt: 'Vitamin E oil' },
        affiliateUrl: 'https://amazon.com/s?k=vitamin+e+oil',
        priceFrom: 6,
      },
      {
        rank: 6,
        productTitle: 'Argan Oil',
        productImage: { src: '/images/argan.jpg', alt: 'Argan oil' },
        affiliateUrl: 'https://amazon.com/s?k=argan+oil',
        priceFrom: 14,
      },
      {
        rank: 7,
        productTitle: 'Sea Buckthorn Oil',
        productImage: { src: '/images/buckthorn.jpg', alt: 'Sea buckthorn oil' },
        affiliateUrl: 'https://amazon.com/s?k=sea+buckthorn',
        priceFrom: 22,
      },
      {
        rank: 8,
        productTitle: 'Apricot Kernel Oil',
        productImage: { src: '/images/apricot.jpg', alt: 'Apricot oil' },
        affiliateUrl: 'https://amazon.com/s?k=apricot+kernel+oil',
        priceFrom: 10,
      },
      {
        rank: 9,
        productTitle: 'Camellia Oil',
        productImage: { src: '/images/camellia.jpg', alt: 'Camellia oil' },
        affiliateUrl: 'https://amazon.com/s?k=camellia+oil',
        priceFrom: 16,
      },
      {
        rank: 10,
        productTitle: 'Hemp Seed Oil',
        productImage: { src: '/images/hemp.jpg', alt: 'Hemp seed oil' },
        affiliateUrl: 'https://amazon.com/s?k=hemp+seed+oil',
        priceFrom: 11,
      },
    ],
  },
  {
    slug: '10-silk-pillowcases',
    title: '10 silk pillowcases worth the splurge',
    category: 'self-care',
    heroImage: { src: '/images/pillowcase.jpg', alt: 'Silk pillowcase', tone: 'sage' },
    readMinutes: 6,
    publishedAt: '2026-05-20',
    updatedAt: '2026-05-20',
    author: authors['maya-patel'],
    rating: 4.7,
    reviewCount: 847,
    excerpt: 'We tested luxury pillowcases and found the ones that actually reduce friction and last years.',
    picks: [
      {
        rank: 1,
        productTitle: 'Premium Silk Pillowcase 100%',
        productImage: { src: '/images/silk1.jpg', alt: 'Silk pillowcase' },
        affiliateUrl: 'https://amazon.com/s?k=silk+pillowcase',
        priceFrom: 45,
        badge: 'best-value',
      },
      {
        rank: 2,
        productTitle: 'Mulberry Silk Pillowcase',
        productImage: { src: '/images/silk2.jpg', alt: 'Mulberry silk' },
        affiliateUrl: 'https://amazon.com/s?k=mulberry+silk',
        priceFrom: 65,
      },
      {
        rank: 3,
        productTitle: 'Charmeuse Silk Pillowcase',
        productImage: { src: '/images/silk3.jpg', alt: 'Charmeuse' },
        affiliateUrl: 'https://amazon.com/s?k=charmeuse+silk',
        priceFrom: 38,
      },
      {
        rank: 4,
        productTitle: 'Luxury Silk Pillowcase Set',
        productImage: { src: '/images/silk4.jpg', alt: 'Silk set' },
        affiliateUrl: 'https://amazon.com/s?k=silk+pillowcase+set',
        priceFrom: 78,
      },
      {
        rank: 5,
        productTitle: 'Bamboo Silk Blend',
        productImage: { src: '/images/silk5.jpg', alt: 'Bamboo silk' },
        affiliateUrl: 'https://amazon.com/s?k=bamboo+silk',
        priceFrom: 28,
      },
      {
        rank: 6,
        productTitle: 'Silk & Satin Pillowcase',
        productImage: { src: '/images/silk6.jpg', alt: 'Silk satin' },
        affiliateUrl: 'https://amazon.com/s?k=silk+satin',
        priceFrom: 35,
      },
      {
        rank: 7,
        productTitle: 'Premium Grade Silk',
        productImage: { src: '/images/silk7.jpg', alt: 'Premium silk' },
        affiliateUrl: 'https://amazon.com/s?k=premium+silk',
        priceFrom: 55,
      },
      {
        rank: 8,
        productTitle: 'Hypoallergenic Silk',
        productImage: { src: '/images/silk8.jpg', alt: 'Hypoallergenic' },
        affiliateUrl: 'https://amazon.com/s?k=hypoallergenic+silk',
        priceFrom: 42,
      },
      {
        rank: 9,
        productTitle: 'Anti-Wrinkle Silk',
        productImage: { src: '/images/silk9.jpg', alt: 'Anti-wrinkle' },
        affiliateUrl: 'https://amazon.com/s?k=anti+wrinkle+silk',
        priceFrom: 48,
      },
      {
        rank: 10,
        productTitle: 'Temperature Silk',
        productImage: { src: '/images/silk10.jpg', alt: 'Temperature silk' },
        affiliateUrl: 'https://amazon.com/s?k=temperature+silk',
        priceFrom: 52,
      },
    ],
  },
  {
    slug: '10-vitamin-c-serums',
    title: '10 vitamin C serums tested over 6 weeks',
    category: 'skincare',
    subCategory: 'Serums & Essences',
    heroImage: { src: '/images/vitc.jpg', alt: 'Vitamin C serums', tone: 'sand' },
    readMinutes: 9,
    publishedAt: '2026-05-18',
    updatedAt: '2026-05-18',
    author: authors['elara-wren'],
    rating: 4.9,
    reviewCount: 1205,
    excerpt: 'We tested every major vitamin C formulation for stability, brightness, and irritation.',
    picks: Array.from({ length: 10 }, (_, i) => ({
      rank: i + 1,
      productTitle: `Vitamin C Serum ${i + 1}`,
      productImage: { src: `/images/vitc${i + 1}.jpg`, alt: `Vitamin C serum ${i + 1}` },
      affiliateUrl: `https://amazon.com/s?k=vitamin+c+serum`,
      priceFrom: 20 + i * 5,
    })),
  },
  {
    slug: '10-magnesium-sprays',
    title: '10 magnesium sprays our editors swear by',
    category: 'wellness',
    subCategory: 'Sleep & Relaxation',
    heroImage: { src: '/images/magnesium.jpg', alt: 'Magnesium spray', tone: 'rose' },
    readMinutes: 7,
    publishedAt: '2026-05-16',
    updatedAt: '2026-05-16',
    author: authors['maya-patel'],
    rating: 4.7,
    picksTestedCount: 62,
    excerpt: 'Real magnesium sprays that actually help us sleep better. We tested absorption, taste, and effectiveness.',
    picks: Array.from({ length: 10 }, (_, i) => ({
      rank: i + 1,
      productTitle: `Magnesium Spray ${i + 1}`,
      productImage: { src: `/images/mag${i + 1}.jpg`, alt: `Magnesium spray ${i + 1}` },
      affiliateUrl: `https://amazon.com/s?k=magnesium+spray`,
      priceFrom: 15 + i * 3,
    })),
  },
  {
    slug: '10-hair-masks',
    title: '10 hair masks that actually repair damage',
    category: 'hair',
    subCategory: 'Deep Conditioning',
    heroImage: { src: '/images/hair-mask.jpg', alt: 'Hair mask', tone: 'mauve' },
    readMinutes: 6,
    publishedAt: '2026-05-15',
    updatedAt: '2026-05-15',
    author: authors['jordan-clark'],
    rating: 4.6,
    reviewCount: 524,
    excerpt: 'We tested 10 weekly hair masks on different hair types and damage levels.',
    picks: Array.from({ length: 10 }, (_, i) => ({
      rank: i + 1,
      productTitle: `Hair Mask ${i + 1}`,
      productImage: { src: `/images/hair${i + 1}.jpg`, alt: `Hair mask ${i + 1}` },
      affiliateUrl: `https://amazon.com/s?k=hair+mask`,
      priceFrom: 12 + i * 2,
    })),
  },
  {
    slug: '10-sleep-pillows',
    title: '10 pillows for better sleep quality',
    category: 'sleep',
    subCategory: 'Bedding',
    heroImage: { src: '/images/pillow.jpg', alt: 'Sleep pillow', tone: 'slate' },
    readMinutes: 8,
    publishedAt: '2026-05-14',
    updatedAt: '2026-05-14',
    author: authors['maya-patel'],
    rating: 4.7,
    reviewCount: 892,
    excerpt: 'Tested for comfort, support, and durability. These pillows actually help you sleep.',
    picks: Array.from({ length: 10 }, (_, i) => ({
      rank: i + 1,
      productTitle: `Sleep Pillow ${i + 1}`,
      productImage: { src: `/images/pillow${i + 1}.jpg`, alt: `Pillow ${i + 1}` },
      affiliateUrl: `https://amazon.com/s?k=pillow`,
      priceFrom: 30 + i * 10,
    })),
  },
  {
    slug: '10-body-lotions',
    title: '10 body lotions for dry winter skin',
    category: 'body',
    subCategory: 'Moisturizers',
    heroImage: { src: '/images/lotion.jpg', alt: 'Body lotion', tone: 'sand' },
    readMinutes: 5,
    publishedAt: '2026-05-13',
    updatedAt: '2026-05-13',
    author: authors['elara-wren'],
    rating: 4.5,
    reviewCount: 667,
    excerpt: 'Rich, nourishing lotions that actually last through the winter.',
    picks: Array.from({ length: 10 }, (_, i) => ({
      rank: i + 1,
      productTitle: `Body Lotion ${i + 1}`,
      productImage: { src: `/images/lotion${i + 1}.jpg`, alt: `Body lotion ${i + 1}` },
      affiliateUrl: `https://amazon.com/s?k=body+lotion`,
      priceFrom: 8 + i * 1.5,
    })),
  },
  {
    slug: '10-face-masks',
    title: '10 face masks that brighten instantly',
    category: 'skincare',
    subCategory: 'Sheet Masks',
    heroImage: { src: '/images/face-mask.jpg', alt: 'Face mask', tone: 'rose' },
    readMinutes: 6,
    publishedAt: '2026-05-12',
    updatedAt: '2026-05-12',
    author: authors['elara-wren'],
    rating: 4.8,
    reviewCount: 1123,
    excerpt: 'Sheet masks that deliver visible results in 15 minutes.',
    picks: Array.from({ length: 10 }, (_, i) => ({
      rank: i + 1,
      productTitle: `Face Mask ${i + 1}`,
      productImage: { src: `/images/mask${i + 1}.jpg`, alt: `Face mask ${i + 1}` },
      affiliateUrl: `https://amazon.com/s?k=face+mask`,
      priceFrom: 3 + i * 0.5,
    })),
  },
  {
    slug: '10-wellness-teas',
    title: '10 wellness teas for better health',
    category: 'wellness',
    subCategory: 'Herbal Teas',
    heroImage: { src: '/images/tea.jpg', alt: 'Wellness tea', tone: 'sage' },
    readMinutes: 7,
    publishedAt: '2026-05-11',
    updatedAt: '2026-05-11',
    author: authors['maya-patel'],
    rating: 4.6,
    reviewCount: 445,
    excerpt: 'Delicious herbal teas that support your wellness goals.',
    picks: Array.from({ length: 10 }, (_, i) => ({
      rank: i + 1,
      productTitle: `Wellness Tea ${i + 1}`,
      productImage: { src: `/images/tea${i + 1}.jpg`, alt: `Tea ${i + 1}` },
      affiliateUrl: `https://amazon.com/s?k=herbal+tea`,
      priceFrom: 6 + i * 1,
    })),
  },
  {
    slug: '10-spring-green-decor',
    title: 'Green is spring\'s it color—master the look at home',
    category: 'home',
    subCategory: 'Spring Decor',
    heroImage: { src: '/images/green-decor.jpg', alt: 'Green spring home decor', tone: 'sage' },
    readMinutes: 8,
    publishedAt: '2026-05-26',
    updatedAt: '2026-05-26',
    author: authors['elara-wren'],
    rating: 4.7,
    reviewCount: 892,
    excerpt: 'Spring\'s most sought-after color is green, and we\'ve found 10 beautiful ways to bring it into your home. From botanical prints to emerald accents, these pieces will transform your space into a lush, inviting sanctuary.',
    picks: [
      {
        rank: 1,
        productTitle: 'Monstera Deliciosa Live Plant in 10" Pot',
        productImage: { src: '/images/monstera.jpg', alt: 'Monstera plant' },
        affiliateUrl: 'https://amazon.com/s?k=monstera+deliciosa+live+plant',
        priceFrom: 32,
        badge: 'editor-pick',
      },
      {
        rank: 2,
        productTitle: 'Botanical Leaf Wall Art Print Set (4 pieces)',
        productImage: { src: '/images/botanical-art.jpg', alt: 'Botanical wall art' },
        affiliateUrl: 'https://amazon.com/s?k=botanical+leaf+wall+art+print',
        priceFrom: 24,
      },
      {
        rank: 3,
        productTitle: 'Emerald Green Velvet Accent Pillow (18x18)',
        productImage: { src: '/images/emerald-pillow.jpg', alt: 'Emerald pillow' },
        affiliateUrl: 'https://amazon.com/s?k=emerald+green+velvet+pillow',
        priceFrom: 28,
        badge: 'best-value',
      },
      {
        rank: 4,
        productTitle: 'Sage Green Ceramic Planter with Drainage (3-pack)',
        productImage: { src: '/images/ceramic-planter.jpg', alt: 'Sage planters' },
        affiliateUrl: 'https://amazon.com/s?k=sage+green+ceramic+planter',
        priceFrom: 18,
      },
      {
        rank: 5,
        productTitle: 'Green and White Striped Table Runner (72" x 14")',
        productImage: { src: '/images/table-runner.jpg', alt: 'Table runner' },
        affiliateUrl: 'https://amazon.com/s?k=green+white+striped+table+runner',
        priceFrom: 22,
      },
      {
        rank: 6,
        productTitle: 'Modern Green Metal Wall Shelf (Set of 2)',
        productImage: { src: '/images/wall-shelf.jpg', alt: 'Metal shelves' },
        affiliateUrl: 'https://amazon.com/s?k=green+metal+wall+shelf',
        priceFrom: 35,
      },
      {
        rank: 7,
        productTitle: 'Leaf Pattern Duvet Cover Set (Queen)',
        productImage: { src: '/images/duvet-cover.jpg', alt: 'Leaf duvet' },
        affiliateUrl: 'https://amazon.com/s?k=leaf+pattern+duvet+cover',
        priceFrom: 42,
      },
      {
        rank: 8,
        productTitle: 'Hanging Glass Terrarium with Geometric Frame',
        productImage: { src: '/images/terrarium.jpg', alt: 'Glass terrarium' },
        affiliateUrl: 'https://amazon.com/s?k=hanging+glass+terrarium+geometric',
        priceFrom: 19,
        badge: 'new',
      },
      {
        rank: 9,
        productTitle: 'Green Linen Curtains (Pair, 84" length)',
        productImage: { src: '/images/curtains.jpg', alt: 'Green curtains' },
        affiliateUrl: 'https://amazon.com/s?k=green+linen+curtains',
        priceFrom: 56,
      },
      {
        rank: 10,
        productTitle: 'Pothos Plant Climbing Moss Pole (36 inches)',
        productImage: { src: '/images/moss-pole.jpg', alt: 'Moss pole plant' },
        affiliateUrl: 'https://amazon.com/s?k=pothos+moss+pole+climbing',
        priceFrom: 15,
      },
    ],
  },
];

export const todayCards: TodayCard[] = [
  {
    meta: "Editor's drop · May 26",
    title: "Today's pick: marula oil",
    href: '/guides/10-face-oils-repurchase',
    tone: 'clay',
  },
  {
    meta: 'Daily ritual',
    title: 'A slower evening routine',
    href: '/guides/10-magnesium-sprays',
    tone: 'sage',
  },
  {
    meta: 'This month',
    title: 'Cozy bath edit · May',
    href: '/',
    tone: 'sand',
  },
  {
    meta: 'To gift',
    title: '10 self-care gifts under $40',
    href: '/',
    tone: 'rose',
  },
  {
    meta: 'Reader fav',
    title: 'The silk pillowcase debate',
    href: '/guides/10-silk-pillowcases',
    tone: 'mauve',
  },
  {
    meta: 'Game of the day',
    title: 'Guess the ingredient',
    href: '/',
    tone: 'slate',
  },
];

export const deals: Deal[] = [
  {
    product: guides[0].picks[0],
    guideSlug: guides[0].slug,
    rankInGuide: 1,
    priceNow: 18,
    priceWas: 32,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const trendingGuides: Guide[] = guides;

export const categor = [
  { name: 'Skincare', slug: 'skincare' },
  { name: 'Hair', slug: 'hair' },
  { name: 'Wellness', slug: 'wellness' },
  { name: 'Sleep', slug: 'sleep' },
  { name: 'Body', slug: 'body' },
  { name: 'Self-care', slug: 'self-care' },
  { name: 'Home', slug: 'home' },
];
